#image: harbor.svc.vkusvill.ru/proxy.docker.io/gradle:jdk11
image: gradle:jdk11

default:
  tags:
    - k8s

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

build:
  stage: build
  script: gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle
